library(data.table)
library(dplyr)
library(xlsx)
library(ggplot2)
th = theme_bw() + theme(
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black")
) + theme(
  legend.position = 'none',
  axis.text.x = element_text(colour = "black", size = 12),
  axis.text.y = element_text(
    colour = "black",
    size = 12,
    hjust = 0.95
  ),
  axis.ticks = element_blank(),
  plot.title = element_text(hjust = 0.5, face = "bold"),
  axis.title = element_text(size = 12, face = "bold")
) + theme(
  strip.placement = "outside",
  plot.title = element_text(hjust = 0.5),
  strip.text.x = element_text(size = 12),
  strip.text.y = element_text(angle = 0, size = 10, face = "italic"),
  panel.spacing = unit(0.1, "lines"),
  strip.background = element_rect(fill = "#EEEEEE", color = "#FFFFFF")
)

#Read TCGA Clinical Data
clin=fread("./data/TCGA_BRCA_Clinical.txt",data.table=F,h=T)%>%mutate(type=ifelse(Age<=50,"young",ifelse(Age>=55,"old","other")))%>%filter(type%in%c("young","old")  & ( as.numeric(as.matrix(HER2))<15.17) & ERstatus=="Positive")%>%mutate(type=factor(type,levels=c("old","young")))

#Read TCGA Breasr Cancer RNA-seq Data
mat<-fread("../data/TCGA_ER_breast_cancer.txt",stringsAsFactors = F,data.table = F)
rownames(mat)=mat$V1
mat=mat[,-1]

#immune signatures genes
signature=read.xlsx("../data/collected_signatures.xlsx",sheetIndex = "R")

sig_lists=list()
for(i in 1:dim(signature)[1]){
  sig_lists[as.character(signature$Short[i])]=list(as.character(strsplit(as.character(signature$Genes[i]),split=",")[[1]]))
}

#estimate the expression signatures by taking the average expression of al member genes in a signature for each individual patient.
mat_signature=NULL
for(sig in names(sig_lists)){
  score=apply(mat[which(rownames(mat)%in%sig_lists[[sig]]),],2,mean)
  mat_signature=rbind(mat_signature,score)
}
rownames(mat_signature)=names(sig_lists)

#zscore normalized signatures
mat_signature_zscore=as.data.frame(cbind(bcr_patient_barcode=colnames(mat_signature),apply(mat_signature,1,function(x)(x-mean(x))/sd(x))))

finalMat=merge(clin,mat_signature_zscore,by="bcr_patient_barcode")

#pairs scatter plot: pairwise comparison
#this part will generate the figure in the slide #9
library(psych)
pdf("./out/signature_correlation.pdf",w=8,h=8)
pairs.panels(finalMat%>%select("MKS","TIS","TCell","BCell","DendriticCell","MastCell","ERS","ERS_liminal","ERS_Pos_Symmans","ERS_Neg_Symmans")%>%mutate_all(~as.numeric(as.matrix(.))), 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE, # show correlation ellipses
             cex=1
)
dev.off()

#compare signatures in young vs old using Mann -Whitney test, donot adjust by any covariates.
##this part will generate the table in the slide #7
ttMW=NULL
for(s in as.character(signature$Short)){
  submat=finalMat[,c("type",s)]
  submat[,s]=as.numeric(as.matrix(submat[,s]))
  
  pvalue=wilcox.test(submat[submat$type=="young",s],submat[submat$type=="old",s])$p.value
  tmpmean=tapply(submat[,s],submat$type,mean)
  ttMW=rbind(ttMW,cbind(Signature=s,'log2 Fold Change'=as.numeric(tmpmean["young"])-as.numeric(tmpmean["old"]),'Mean in Young'=tmpmean["young"],'Mean in Old'=tmpmean["old"],Pvalue=pvalue))
}

ttMW=as.data.frame(ttMW)
ttMW$Pvalue=as.numeric(as.matrix(ttMW$Pvalue))
ttMW$FDR=p.adjust(ttMW$Pvalue,method="fdr")

ttMW$`log2 Fold Change`=as.numeric(as.matrix(ttMW$`log2 Fold Change`))
ttMW$`Mean in Young`=as.numeric(as.matrix(ttMW$`Mean in Young`))
ttMW$`Mean in Old`=as.numeric(as.matrix(ttMW$`Mean in Old`))

write.xlsx(ttMW,"./out/TCGA_BRCA_Signature_YoungVsOld.xlsx")

#violion plot compare signatures in young vs old: p value was generated by Mann -Whitney test
##this part will generate the figures in the slide #8
for(s in as.character(signature$Short)){
  submat=finalMat[,c("type",s)]
  colnames(submat)[2]="Signature"
  med <- submat %>%
    group_by(type) %>% 
    filter(!is.na(type)) %>%
    summarize(med = median(as.numeric(as.matrix(Signature))))
  
  if(ttMW$Pvalue[ttMW$Signature==s]<0.0001){
    pvalue<-formatC(ttMW$Pvalue[ttMW$Signature==s], format = "e", digits = 2)
  }else{
    pvalue=round(ttMW$Pvalue[ttMW$Signature==s],digits=4)
  }
  
  if(ttMW$FDR[ttMW$Signature==s]<0.0001){
    FDR<-formatC(ttMW$FDR[ttMW$Signature==s], format = "e", digits = 2)
  }else{
    FDR=round(ttMW$FDR[ttMW$Signature==s],digits=4)
  }
  
  p=ggplot(submat,
           aes(x=type,y=as.numeric(as.matrix(Signature)))) + 
    geom_violin() + 
    geom_jitter(alpha=.1,width = .1,size=.2)+th+ggtitle(paste0("p value=",pvalue,"\nFDR=",FDR))+xlab("")+ylab(s)+
    geom_segment(data = med, 
                 aes(y=med,yend=med,x=as.numeric(type)-.2,
                     xend=as.numeric(type)+.2),color="red")
  fn=paste0("./out/",s,"_wilcox.pdf")
  ggsave(fn,w = 3, h = 3, useDingbat=F,limitsize = FALSE)
}


#include clinical covariates in our analysis
#we didn't show the following analysis in our slides.
#estimate the association between age group and expression signatures, adjusted by covariates. model: gene-expression signature ~ age group (young vs old) + race + lymphnodes status + pathologic stage
tt=NULL
for(s in as.character(signature$Short)){
  model=paste0("as.numeric(",s,")~type+Race+lymphnodes_status+pathologic_stage")#+race+number_of_lymphnodes_positive_by_he+pathologic_stage
  fit=glm(formula=model,data=finalMat,family=gaussian(link = "identity"))
  stats = data.frame(summary(fit)$coefficients)["typeyoung",]
  tt=rbind(tt,stats)
}

rownames(tt)=NULL
tt=cbind(Signature=as.character(signature$Short),tt)
tt$Signature=as.character(tt$Signature)
tt$FDR=p.adjust(tt$Pr...t..,method="fdr")

write.table(tt,"./out/TCGA_ERPos_Age_Signature_Association.txt",sep="\t")

#violion plot compare signatures in young vs old: p value was generated by the regression analysis adjusted by covariates 
for(s in as.character(signature$Short)){
  submat=finalMat[,c("type",s)]
  colnames(submat)[2]="Signature"
  pvalue=round(tt[tt$Signature==s,"Pr...t.."],digits=4)
  FDR=round(tt[tt$Signature==s,"FDR"],digits=4)
  
  med <- submat %>%
    group_by(type) %>% 
    filter(!is.na(type)) %>%
    summarize(med = median(as.numeric(as.matrix(Signature))))
  
  p=ggplot(submat,
           aes(x=type,y=as.numeric(as.matrix(Signature)))) + 
    geom_violin() + 
    geom_jitter(alpha=.1,width = .1,size=.2)+th+ggtitle(paste0("p value=",pvalue,"\nFDR=",FDR))+xlab("")+ylab(s)+
    geom_segment(data = med, 
                 aes(y=med,yend=med,x=as.numeric(type)-.2,
                     xend=as.numeric(type)+.2),color="red")
  fn=paste0("./out/",s,".pdf")
  ggsave(fn,w = 3, h = 3, useDingbat=F,limitsize = FALSE)
}


